# Generated by Django 2.2 on 2019-04-24 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DouBanTop250', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bilibili',
        ),
    ]
