# Generated by Django 2.0 on 2019-04-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DouBanTop250', '0002_delete_bilibili'),
    ]

    operations = [
        migrations.CreateModel(
            name='douban',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(blank=True, max_length=255, null=True)),
                ('d_other', models.CharField(blank=True, max_length=255, null=True)),
                ('d_direct', models.CharField(blank=True, max_length=255, null=True)),
                ('d_year', models.CharField(blank=True, max_length=255, null=True)),
                ('d_from', models.CharField(blank=True, max_length=255, null=True)),
                ('d_type', models.CharField(blank=True, max_length=255, null=True)),
                ('d_content', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
